# Yêu cầu plugin: MythicMobs v4.7.2   -  TokenManager
# Code bởi Cortez_Romeo

# Random drop tokens 
# Min-Max: Giới hạn số token có thể drop
drop:
  tokens:
    # Khi mobs trong mythicmobs không có tren trong danh sách
    # thì số token rớt ra sẽ theo vào phần default:
    # Hãy đảm bảo không đặt tên mobs là "default" 
    default:
      min: 1  
      max: 10
    bossLv1:
      min: 50
      max: 100
    bossXYZ:
      min: 400
      max: 500    
    
  message: "&fBạn nhận được &e%tokens% &ftokens!"
  boosterMessage: "&c(BOOSTER) &fBạn nhận được &e%tokens% &a(x%booster%) &etokens!" 
booster:
  activeBoosterMessage: "&fKích hoạt &ex%booster% tokens&f khi giết mobs trong &e%time% giây &fthành công!"
  expiredBoosterMessage: "&cBooster x%booster% token khi giết mobs vừa hết hạn!"
  